# Generated by Django 6.0.1 on 2026-01-21 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Baggage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_name', models.CharField(max_length=100)),
                ('tag_id', models.CharField(help_text='Example: FJ12345', max_length=20, unique=True)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_overweight', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('CHECKED_IN', 'Checked-In at Counter'), ('SECURITY', 'Security Cleared'), ('LOADED', 'Loaded on Aircraft'), ('OFFLOADED', 'Offloaded / Security Alert')], default='CHECKED_IN', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bags', to='flights.flight')),
            ],
        ),
    ]
